Users:
    type: entity
    table: users
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 127
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        password:
            type: string
            length: 255
            fixed: false
            nullable: false
        salt:
            type: string
            length: 32
            fixed: false
            nullable: false
    manyToMany:
        club:
            targetEntity: Clubs
            cascade: {  }
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
        event:
            targetEntity: Events
            cascade: {  }
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
