<?php

namespace Nerdery\GroupsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubsRepository extends EntityRepository
{
}
